@startuml

hide circle
title UML-diagram of conceptual classes of the Software Product

Class User {
    name
    age
    eMail
}

Class Doctor {
    name
    eMail
    workExperience
    workplace
    specialization
}

Class Advice {
    title
    description
    dateAdded
    rating
}

Class "Advice category" {
    theme
}

Class "Detailed information" {
    title
    dateAdded
    rating
    content
}

Class Catalogue {
    theme
    dateCreated
}

Class Document {
    title
    content
    dateCreated
}

Class Keyword {
    word
}

Class "Important text" {
    textPart
}

Class Note {
    title
    textPart
    dateCreated
}

"Advice category" o-- Advice

Advice o-- "Detailed information"

Catalogue o-- Document

Document o-- Keyword

Document o-- "Important text"

Doctor"1" --> "+"Advice : creates

User"+" --> "+"Advice : sorts 

User"+" --> "+""Detailed information" : looks through 

User"1" --> "+"Catalogue : creates

User"1" --> "+"Document : organizes

User"1" --> "+"Keyword : looks for

User"1" --> "+""Important text" : highlights

User"1" --> "+"Note : creates

Note"+" --> "+""Important text" : contains

@enduml
