@startuml

title Універсальний програмний продукт

left to right direction

actor :Здоровий споживач:
actor Робітник
actor Продавець
actor :Нова пошта:

rectangle "Програмний комплекс" {

    usecase (Створення скульптур)
    usecase (Формування Online-заявки на публікацію медіа)
    usecase (Перевірка якості медіа)
    usecase (Публікація медіа)
    usecase (Організація документів в Online-додатку)
    usecase (Перегляд та пошук документів)
    usecase (Перегляд переліку їжі в Online-магазині)
    usecase (Формування Online-замовлення на їжу)
    usecase (Формування споживчого пакету)
    usecase (Відправка споживчого пакету)
    usecase (Отримання споживчого пакету)
    usecase (Перегляд порад щодо покращення здоров'я)
    usecase (Відстеження фізичних параметрів та результатів занять спортом)

    :Здоровий споживач: -- (Створення скульптур)
    :Здоровий споживач: -- (Формування Online-заявки на публікацію медіа)
    (Перевірка якості медіа) -- Робітник
    (Публікація медіа) -- Робітник
    :Здоровий споживач: -- (Організація документів в Online-додатку)
    :Здоровий споживач: -- (Перегляд та пошук документів)
    :Здоровий споживач: -- (Перегляд переліку їжі в Online-магазині)
    :Здоровий споживач: -- (Формування Online-замовлення на їжу)
    (Формування споживчого пакету) -- Продавець
    (Відправка споживчого пакету) -- Продавець
    (Відправка споживчого пакету) -- :Нова пошта:
    (Отримання споживчого пакету) .> (Відправка споживчого пакету) : include
    :Здоровий споживач: -- (Отримання споживчого пакету)
    :Здоровий споживач: -- (Перегляд порад щодо покращення здоров'я)
    :Здоровий споживач: -- (Відстеження фізичних параметрів та результатів занять спортом)
}

@enduml